// This file is auto-generated by @hey-api/openapi-ts

export const ArpTablePublicSchema = {
    properties: {
        switch_id: {
            type: 'string',
            format: 'uuid',
            title: 'Switch Id',
            description: '关联的 Switch id'
        },
        ip: {
            type: 'string',
            maxLength: 20,
            title: 'Ip',
            description: 'IP地址',
            default: ''
        },
        mac: {
            type: 'string',
            maxLength: 20,
            title: 'Mac',
            description: 'MAC地址',
            default: ''
        },
        interface: {
            type: 'string',
            maxLength: 50,
            title: 'Interface',
            description: '接口',
            default: ''
        },
        vlan: {
            type: 'string',
            title: 'Vlan',
            description: 'VLAN',
            default: ''
        },
        updated: {
            type: 'string',
            format: 'date-time',
            title: 'Updated',
            description: '更新时间'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        switch: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/SwitchLite'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    required: ['switch_id', 'id', 'switch'],
    title: 'ArpTablePublic'
} as const;

export const ArpTablesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ArpTablePublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ArpTablesPublic'
} as const;

export const BackupJobCreateSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        job_type: {
            type: 'string',
            pattern: '^(full_backup|failed_backup)$',
            title: 'Job Type'
        },
        cron: {
            type: 'string',
            title: 'Cron',
            description: 'Cron 表达式，例如: 0 2 * * *'
        },
        enabled: {
            type: 'boolean',
            title: 'Enabled',
            default: true
        }
    },
    type: 'object',
    required: ['name', 'job_type', 'cron'],
    title: 'BackupJobCreate'
} as const;

export const BackupJobUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        job_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^(full_backup|failed_backup)$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Job Type'
        },
        cron: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cron'
        },
        enabled: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Enabled'
        }
    },
    type: 'object',
    required: ['job_type'],
    title: 'BackupJobUpdate'
} as const;

export const BackupSchedulerSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        job_id: {
            type: 'string',
            title: 'Job Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        job_type: {
            type: 'string',
            title: 'Job Type'
        },
        cron: {
            type: 'string',
            title: 'Cron'
        },
        enabled: {
            type: 'boolean',
            title: 'Enabled',
            default: true
        },
        kwargs: {
            anyOf: [
                {
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Kwargs'
        },
        last_run_time: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Run Time'
        },
        next_run_time: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Next Run Time'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At',
            description: '创建时间'
        }
    },
    type: 'object',
    required: ['job_id', 'name', 'job_type', 'cron'],
    title: 'BackupScheduler'
} as const;

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: 'password'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const Body_switches_import_switchesSchema = {
    properties: {
        file: {
            type: 'string',
            format: 'binary',
            title: 'File'
        }
    },
    type: 'object',
    required: ['file'],
    title: 'Body_switches-import_switches'
} as const;

export const BranchCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 20,
            title: 'Name',
            description: '分支名称'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'BranchCreate'
} as const;

export const BranchPublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 20,
            title: 'Name',
            description: '分支名称'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['name', 'id'],
    title: 'BranchPublic'
} as const;

export const BranchUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        }
    },
    type: 'object',
    title: 'BranchUpdate'
} as const;

export const BranchesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/BranchPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'BranchesPublic'
} as const;

export const DashboardSchema = {
    properties: {
        switch_backup_count: {
            type: 'integer',
            title: 'Switch Backup Count'
        },
        switch_backup_error_count: {
            type: 'integer',
            title: 'Switch Backup Error Count',
            default: 0
        },
        vrf_count: {
            type: 'integer',
            title: 'Vrf Count'
        },
        vrf_diff_count: {
            type: 'integer',
            title: 'Vrf Diff Count'
        },
        iptable_count: {
            type: 'integer',
            title: 'Iptable Count'
        },
        iptable_diff_count: {
            type: 'integer',
            title: 'Iptable Diff Count'
        },
        config_diff_count: {
            type: 'integer',
            title: 'Config Diff Count'
        }
    },
    type: 'object',
    required: ['switch_backup_count', 'vrf_count', 'vrf_diff_count', 'iptable_count', 'iptable_diff_count', 'config_diff_count'],
    title: 'Dashboard'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const IPtablePublicSchema = {
    properties: {
        switch_id: {
            type: 'string',
            format: 'uuid',
            title: 'Switch Id',
            description: '关联的 Switch id'
        },
        interface: {
            type: 'string',
            maxLength: 50,
            title: 'Interface',
            description: '接口',
            default: ''
        },
        ip: {
            type: 'string',
            maxLength: 20,
            title: 'Ip',
            description: '管理IP',
            default: ''
        },
        mask: {
            type: 'integer',
            title: 'Mask',
            description: '掩码',
            default: 0
        },
        vrf: {
            type: 'string',
            maxLength: 50,
            title: 'Vrf',
            description: 'VRF',
            default: ''
        },
        acl: {
            type: 'string',
            maxLength: 20,
            title: 'Acl',
            description: 'ACL',
            default: ''
        },
        status: {
            type: 'string',
            title: 'Status',
            description: '状态',
            default: ''
        },
        created: {
            type: 'string',
            format: 'date',
            title: 'Created',
            description: '创建日期（仅日期）'
        },
        updated: {
            type: 'string',
            format: 'date-time',
            title: 'Updated',
            description: '更新时间'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        switch: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/SwitchLite'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    required: ['switch_id', 'id', 'switch'],
    title: 'IPtablePublic'
} as const;

export const IPtablesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/IPtablePublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'IPtablesPublic'
} as const;

export const InspectorCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 20,
            title: 'Name',
            description: '巡检账号名'
        },
        password: {
            type: 'string',
            maxLength: 40,
            title: 'Password',
            description: '巡检密码'
        },
        description: {
            type: 'string',
            maxLength: 50,
            title: 'Description',
            description: '账号描述',
            default: 'default'
        }
    },
    type: 'object',
    required: ['name', 'password'],
    title: 'InspectorCreate'
} as const;

export const InspectorPublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 20,
            title: 'Name',
            description: '巡检账号名'
        },
        password: {
            type: 'string',
            maxLength: 40,
            title: 'Password',
            description: '巡检密码'
        },
        description: {
            type: 'string',
            maxLength: 50,
            title: 'Description',
            description: '账号描述',
            default: 'default'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['name', 'password', 'id'],
    title: 'InspectorPublic'
} as const;

export const InspectorUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 40
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    title: 'InspectorUpdate'
} as const;

export const InspectorsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/InspectorPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'InspectorsPublic'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 40,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const SwitchSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 80,
            minLength: 1,
            title: 'Name',
            description: '设备名'
        },
        ip: {
            type: 'string',
            maxLength: 20,
            minLength: 1,
            title: 'Ip',
            description: '管理IP'
        },
        port: {
            type: 'integer',
            title: 'Port',
            description: '管理端口',
            default: 22
        },
        status: {
            type: 'boolean',
            title: 'Status',
            description: '状态',
            default: true
        },
        stack_num: {
            type: 'integer',
            title: 'Stack Num',
            description: '堆叠数量',
            default: 1
        },
        stype: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'Stype',
            description: '操作系统型号'
        },
        software_version: {
            type: 'string',
            maxLength: 50,
            title: 'Software Version',
            description: '软件版本',
            default: ''
        },
        hardware_type: {
            type: 'string',
            maxLength: 30,
            title: 'Hardware Type',
            description: '硬件型号',
            default: ''
        },
        description: {
            type: 'string',
            maxLength: 50,
            title: 'Description',
            description: '描述',
            default: '-'
        },
        sn: {
            type: 'string',
            maxLength: 250,
            title: 'Sn',
            description: '序列号',
            default: '-'
        },
        add_date: {
            type: 'string',
            format: 'date',
            title: 'Add Date',
            description: '添加日期'
        },
        mod_date: {
            type: 'string',
            format: 'date-time',
            title: 'Mod Date',
            description: '修改日期'
        },
        branch_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Branch Id',
            description: '分支ID'
        },
        login_type_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Login Type Id',
            description: '登录方式ID'
        },
        inspector_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Inspector Id',
            description: '巡检账号ID'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['name', 'ip'],
    title: 'Switch'
} as const;

export const SwitchConfigBaseSchema = {
    properties: {
        switch_id: {
            type: 'string',
            format: 'uuid',
            title: 'Switch Id',
            description: '关联的 Switch id'
        },
        status: {
            type: 'string',
            maxLength: 50,
            title: 'Status',
            description: '当天备份状态',
            default: 'null'
        },
        config_path: {
            type: 'string',
            maxLength: 100,
            title: 'Config Path',
            description: '配置文件路径',
            default: ''
        },
        created: {
            type: 'string',
            format: 'date',
            title: 'Created',
            description: '备份日期（仅日期）'
        },
        updated: {
            type: 'string',
            format: 'date-time',
            title: 'Updated',
            description: '更新时间'
        }
    },
    type: 'object',
    required: ['switch_id'],
    title: 'SwitchConfigBase'
} as const;

export const SwitchConfigDiffShowSchema = {
    properties: {
        date_list: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Date List'
        },
        content: {
            type: 'string',
            title: 'Content'
        },
        current_date: {
            type: 'string',
            title: 'Current Date'
        }
    },
    type: 'object',
    required: ['date_list', 'content', 'current_date'],
    title: 'SwitchConfigDiffShow'
} as const;

export const SwitchConfigShowSchema = {
    properties: {
        content: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Content'
        },
        switch: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/SwitchLite'
                },
                {
                    type: 'null'
                }
            ]
        },
        created: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created'
        },
        updated: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated'
        },
        date_list: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Date List'
        }
    },
    type: 'object',
    required: ['content', 'switch', 'created', 'updated', 'date_list'],
    title: 'SwitchConfigShow'
} as const;

export const SwitchCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 80,
            minLength: 1,
            title: 'Name',
            description: '设备名'
        },
        ip: {
            type: 'string',
            maxLength: 20,
            minLength: 1,
            title: 'Ip',
            description: '管理IP'
        },
        port: {
            type: 'integer',
            title: 'Port',
            description: '管理端口',
            default: 22
        },
        status: {
            type: 'boolean',
            title: 'Status',
            description: '状态',
            default: true
        },
        stack_num: {
            type: 'integer',
            title: 'Stack Num',
            description: '堆叠数量',
            default: 1
        },
        stype: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'Stype',
            description: '操作系统型号'
        },
        software_version: {
            type: 'string',
            maxLength: 50,
            title: 'Software Version',
            description: '软件版本',
            default: ''
        },
        hardware_type: {
            type: 'string',
            maxLength: 30,
            title: 'Hardware Type',
            description: '硬件型号',
            default: ''
        },
        description: {
            type: 'string',
            maxLength: 50,
            title: 'Description',
            description: '描述',
            default: '-'
        },
        sn: {
            type: 'string',
            maxLength: 250,
            title: 'Sn',
            description: '序列号',
            default: '-'
        },
        add_date: {
            type: 'string',
            format: 'date',
            title: 'Add Date',
            description: '添加日期'
        },
        mod_date: {
            type: 'string',
            format: 'date-time',
            title: 'Mod Date',
            description: '修改日期'
        },
        branch_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Branch Id',
            description: '分支ID'
        },
        login_type_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Login Type Id',
            description: '登录方式ID'
        },
        inspector_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Inspector Id',
            description: '巡检账号ID'
        }
    },
    type: 'object',
    required: ['name', 'ip'],
    title: 'SwitchCreate'
} as const;

export const SwitchListSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        }
    },
    type: 'object',
    required: ['id', 'name'],
    title: 'SwitchList'
} as const;

export const SwitchLiteSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        ip: {
            type: 'string',
            title: 'Ip'
        },
        stack_num: {
            type: 'integer',
            title: 'Stack Num'
        },
        branch: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/BranchPublic'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    required: ['id', 'name', 'ip', 'stack_num', 'branch'],
    title: 'SwitchLite'
} as const;

export const SwitchLoginTypePublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 20,
            title: 'Name',
            description: '登录方式',
            default: 'ssh'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['id'],
    title: 'SwitchLoginTypePublic'
} as const;

export const SwitchLoginTypesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/SwitchLoginTypePublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'SwitchLoginTypesPublic'
} as const;

export const SwitchPublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 80,
            minLength: 1,
            title: 'Name',
            description: '设备名'
        },
        ip: {
            type: 'string',
            maxLength: 20,
            minLength: 1,
            title: 'Ip',
            description: '管理IP'
        },
        port: {
            type: 'integer',
            title: 'Port',
            description: '管理端口',
            default: 22
        },
        status: {
            type: 'boolean',
            title: 'Status',
            description: '状态',
            default: true
        },
        stack_num: {
            type: 'integer',
            title: 'Stack Num',
            description: '堆叠数量',
            default: 1
        },
        stype: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'Stype',
            description: '操作系统型号'
        },
        software_version: {
            type: 'string',
            maxLength: 50,
            title: 'Software Version',
            description: '软件版本',
            default: ''
        },
        hardware_type: {
            type: 'string',
            maxLength: 30,
            title: 'Hardware Type',
            description: '硬件型号',
            default: ''
        },
        description: {
            type: 'string',
            maxLength: 50,
            title: 'Description',
            description: '描述',
            default: '-'
        },
        sn: {
            type: 'string',
            maxLength: 250,
            title: 'Sn',
            description: '序列号',
            default: '-'
        },
        add_date: {
            type: 'string',
            format: 'date',
            title: 'Add Date',
            description: '添加日期'
        },
        mod_date: {
            type: 'string',
            format: 'date-time',
            title: 'Mod Date',
            description: '修改日期'
        },
        branch_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Branch Id',
            description: '分支ID'
        },
        login_type_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Login Type Id',
            description: '登录方式ID'
        },
        inspector_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Inspector Id',
            description: '巡检账号ID'
        },
        branch: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/BranchPublic'
                },
                {
                    type: 'null'
                }
            ]
        },
        login_type: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/SwitchLoginTypePublic'
                },
                {
                    type: 'null'
                }
            ]
        },
        inspector: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/InspectorPublic'
                },
                {
                    type: 'null'
                }
            ]
        },
        latest_config: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/SwitchConfigBase'
                },
                {
                    type: 'null'
                }
            ]
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['name', 'ip', 'branch', 'login_type', 'inspector', 'latest_config', 'id'],
    title: 'SwitchPublic'
} as const;

export const SwitchUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 80
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        ip: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'Ip'
        },
        status: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Status'
        },
        stack: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Stack'
        },
        stype: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'Stype'
        },
        software_version: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Software Version'
        },
        hardware_type: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 30
                },
                {
                    type: 'null'
                }
            ],
            title: 'Hardware Type'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        sn: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 250
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sn'
        },
        branch_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Branch Id'
        },
        login_type_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Login Type Id'
        },
        inspector_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Inspector Id'
        }
    },
    type: 'object',
    title: 'SwitchUpdate'
} as const;

export const SwitchesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/SwitchPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'SwitchesPublic'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 40,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 40,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 40,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 40,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 40,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;

export const VrfPublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 50,
            title: 'Name',
            description: 'VRF名称',
            default: ''
        },
        rd: {
            type: 'string',
            title: 'Rd'
        },
        rt: {
            type: 'string',
            maxLength: 20,
            title: 'Rt',
            description: '路由 target',
            default: ''
        },
        description: {
            type: 'string',
            maxLength: 50,
            title: 'Description',
            description: '描述',
            default: ''
        }
    },
    type: 'object',
    required: ['rd'],
    title: 'VrfPublic'
} as const;

export const VrfsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/VrfPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'VrfsPublic'
} as const;