"""alter switch tables

Revision ID: 041598e060d3
Revises: cf3c6f74dbc7
Create Date: 2025-10-17 09:58:44.552286

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '041598e060d3'
down_revision = 'cf3c6f74dbc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('switchconfig_switch_id_fkey', 'switchconfig', type_='foreignkey')
    op.create_foreign_key(None, 'switchconfig', 'switch', ['switch_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'switchconfig', type_='foreignkey')
    op.create_foreign_key('switchconfig_switch_id_fkey', 'switchconfig', 'switch', ['switch_id'], ['id'])
    # ### end Alembic commands ###
