"""alter ip tables

Revision ID: 16157961f997
Revises: 041598e060d3
Create Date: 2025-10-17 09:59:47.271284

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '16157961f997'
down_revision = '041598e060d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('iptables_switch_id_fkey', 'iptables', type_='foreignkey')
    op.create_foreign_key(None, 'iptables', 'switch', ['switch_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'iptables', type_='foreignkey')
    op.create_foreign_key('iptables_switch_id_fkey', 'iptables', 'switch', ['switch_id'], ['id'])
    # ### end Alembic commands ###
