"""add arp-vrf tables

Revision ID: 1cb666a1ce5c
Revises: 68044034d2a9
Create Date: 2025-10-15 10:32:41.454116

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '1cb666a1ce5c'
down_revision = '68044034d2a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
