"""add ip tables

Revision ID: 5134b1100ad3
Revises: bc4d8e11d2a0
Create Date: 2025-10-14 14:47:09.235821

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '5134b1100ad3'
down_revision = 'bc4d8e11d2a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('iptables',
    sa.Column('switch_id', sa.Uuid(), nullable=False),
    sa.Column('interface', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('ip', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('mask', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created', sa.Date(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['switch_id'], ['switch.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('iptables')
    # ### end Alembic commands ###
