"""switch configs desc

Revision ID: 5191d5804669
Revises: b222d5a19f9e
Create Date: 2025-10-14 10:33:08.387720

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '5191d5804669'
down_revision = 'b222d5a19f9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
