"""add switch tables

Revision ID: 56e979c2e7b0
Revises: 1a31ce608336
Create Date: 2025-09-27 17:13:54.168570

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '56e979c2e7b0'
down_revision = '1a31ce608336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branch',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inspector',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('switchlogintype',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('switch',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('ip', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('stack_num', sa.Integer(), nullable=False),
    sa.Column('stype', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('software_version', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('hardware_type', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('sn', sqlmodel.sql.sqltypes.AutoString(length=250), nullable=False),
    sa.Column('add_date', sa.Date(), nullable=False),
    sa.Column('mod_date', sa.DateTime(), nullable=False),
    sa.Column('branch_id', sa.Uuid(), nullable=True),
    sa.Column('login_type_id', sa.Uuid(), nullable=True),
    sa.Column('inspector_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branch.id'], ),
    sa.ForeignKeyConstraint(['inspector_id'], ['inspector.id'], ),
    sa.ForeignKeyConstraint(['login_type_id'], ['switchlogintype.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('switch')
    op.drop_table('switchlogintype')
    op.drop_table('inspector')
    op.drop_table('branch')
    # ### end Alembic commands ###
