"""add arp-vrf tables

Revision ID: 68044034d2a9
Revises: d30d1038ac9d
Create Date: 2025-10-15 10:08:16.785092

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '68044034d2a9'
down_revision = 'd30d1038ac9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vrf',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('rd', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('rt', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.PrimaryKeyConstraint('rd')
    )
    op.create_table('arptable',
    sa.Column('swithch_id', sa.Uuid(), nullable=False),
    sa.Column('ip', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('mac', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('interface', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('vlan', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['swithch_id'], ['switch.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('arptable')
    op.drop_table('vrf')
    # ### end Alembic commands ###
