"""add statistics data

Revision ID: 76232d05a68c
Revises: 91e339728f78
Create Date: 2026-03-13 10:16:48.305446

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '76232d05a68c'
down_revision = '91e339728f78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('everydaystatistics',
    sa.Column('add_date', sa.Date(), nullable=False),
    sa.Column('vrf_count', sa.Integer(), nullable=False),
    sa.Column('vrf_different_count', sa.Integer(), nullable=False),
    sa.Column('ip_count', sa.Integer(), nullable=False),
    sa.Column('ip_different_count', sa.Integer(), nullable=False),
    sa.Column('switch_different_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('everydaystatistics')
    # ### end Alembic commands ###
