"""add switch port

Revision ID: 7d5a037f5838
Revises: eda140e50e6f
Create Date: 2026-03-10 11:11:31.768836

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '7d5a037f5838'
down_revision = 'eda140e50e6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('switch', sa.Column('port', sa.Integer(), nullable=False, server_default="22"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('switch', 'port')
    # ### end Alembic commands ###
