"""fix arp model switch id error

Revision ID: 8d29a17b90f9
Revises: e8bd8bc308d7
Create Date: 2026-03-24 10:13:42.728676

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '8d29a17b90f9'
down_revision = 'e8bd8bc308d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('arptable', sa.Column('switch_id', sa.Uuid(), nullable=False))
    op.create_index(op.f('ix_arptable_switch_id'), 'arptable', ['switch_id'], unique=False)
    op.drop_constraint('arptable_swithch_id_fkey', 'arptable', type_='foreignkey')
    op.create_foreign_key(None, 'arptable', 'switch', ['switch_id'], ['id'], ondelete='CASCADE')
    op.drop_column('arptable', 'swithch_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('arptable', sa.Column('swithch_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'arptable', type_='foreignkey')
    op.create_foreign_key('arptable_swithch_id_fkey', 'arptable', 'switch', ['swithch_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_arptable_switch_id'), table_name='arptable')
    op.drop_column('arptable', 'switch_id')
    # ### end Alembic commands ###
