"""arptable relation fix

Revision ID: 91e339728f78
Revises: 7d5a037f5838
Create Date: 2026-03-12 14:14:23.433168

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '91e339728f78'
down_revision = '7d5a037f5838'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('arptable_swithch_id_fkey', 'arptable', type_='foreignkey')
    op.create_foreign_key(None, 'arptable', 'switch', ['swithch_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'arptable', type_='foreignkey')
    op.create_foreign_key('arptable_swithch_id_fkey', 'arptable', 'switch', ['swithch_id'], ['id'])
    # ### end Alembic commands ###
