"""alter ip tables

Revision ID: 95d0d55d3e50
Revises: 5134b1100ad3
Create Date: 2025-10-14 15:22:05.232677

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '95d0d55d3e50'
down_revision = '5134b1100ad3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('iptables', sa.Column('vrf', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False))
    op.add_column('iptables', sa.Column('acl', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('iptables', 'acl')
    op.drop_column('iptables', 'vrf')
    # ### end Alembic commands ###
