"""add unique constraint uq_branch_name to branch.name

Revision ID: b222d5a19f9e
Revises: d72aa413d3ad
Create Date: 2025-10-10 16:00:29.588848

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b222d5a19f9e'
down_revision = 'd72aa413d3ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_branch_name', 'branch', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_branch_name', 'branch', type_='unique')
    # ### end Alembic commands ###
