"""alter arp tables

Revision ID: bc38db516be0
Revises: 38bdcca1f905
Create Date: 2025-10-15 11:00:47.681440

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'bc38db516be0'
down_revision = '38bdcca1f905'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('arptable', sa.Column('updated', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('arptable', 'updated')
    # ### end Alembic commands ###
