"""add switch latest_config

Revision ID: bc4d8e11d2a0
Revises: d035faed72be
Create Date: 2025-10-14 10:48:34.206998

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'bc4d8e11d2a0'
down_revision = 'd035faed72be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
