"""alter switch tables

Revision ID: cf3c6f74dbc7
Revises: dd7d7f7e0774
Create Date: 2025-10-17 09:56:39.133198

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'cf3c6f74dbc7'
down_revision = 'dd7d7f7e0774'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
