"""add switch config table

Revision ID: d72aa413d3ad
Revises: 56e979c2e7b0
Create Date: 2025-10-06 11:36:53.787386

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd72aa413d3ad'
down_revision = '56e979c2e7b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('switchconfig',
    sa.Column('switch_id', sa.Uuid(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('config_path', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('created', sa.Date(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['switch_id'], ['switch.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('switch_id', 'created', name='uq_switch_created')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('switchconfig')
    # ### end Alembic commands ###
