"""alter switch tables

Revision ID: dd7d7f7e0774
Revises: bc38db516be0
Create Date: 2025-10-17 09:55:43.083907

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'dd7d7f7e0774'
down_revision = 'bc38db516be0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
