"""add switchconfig indexes

Revision ID: eda140e50e6f
Revises: f1c2d3e4f5a6
Create Date: 2026-03-07 18:03:11.874963

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'eda140e50e6f'
down_revision = 'f1c2d3e4f5a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_switch_status_created', 'switchconfig', ['switch_id', 'status', 'created'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_switch_status_created', table_name='switchconfig')
    # ### end Alembic commands ###
